### PR TITLE
make artifact discoverable by jitpack

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
In [build log](https://jitpack.io/com/github/mukel/telegrambot4s_2.12/f1d6288ffe/build.log), last line says:
`No build artifacts found`
probably because the artifact name was /home/jitpack/.m2/repository/**info/mukel/telegrambot4s_2.12**/2.9.1-SNAPSHOT/telegrambot4s_2.12-2.9.1-SNAPSHOT.jar

You could also follow https://jitpack.io/docs/#custom-domain-name to make artifacts downloadable as `"info.mukel" %% "telegrambot4s" % ...`

**Comment by mukel** [comment]
OK I'll make it work for my domain. Thanks for the hint.

**Comment by ilya-epifanov** [comment]
BTW, I can't find any artifacts in sonatype: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22info.mukel%22

**Comment by mukel** [comment]
I've been​ publishing SNAPSHOTs, but it's already time to have a release.

**Comment by mukel** [comment]
I worked out the custom domain, but Jitpack still doesn't work. It's been broken for quite some time already, so I think I'll finally drop Jitpack.
You can check the logs in https://jitpack.io/#info.mukel/telegrambot4s , the build succeeds, but then nothing is published. Similar issues are being closed without answer on the Jitpack issues repo.

**Comment by mukel** [comment]
The library is finally published on Maven central.
I removed Jitpack instructions from README. Jitpack it's working fine, even with my custom domain "info.mukel", so feel free to use it as well.

**Pull request closed without merging**
